<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>EPDiag</AssemblyName>
    <RootNamespace>EPDiag</RootNamespace>
    <Version>1.0.0</Version>
    <LangVersion>latest</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <NoWarn>$(NoWarn);CS0618;CS0649;CS0169</NoWarn>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <Import Project="Local.props" Condition="Exists('Local.props')" />

  <PropertyGroup>
    <GameManaged Condition="'$(GameManaged)' == ''">C:\Program Files (x86)\Steam\steamapps\common\ROUNDS\Rounds_Data\Managed</GameManaged>
    <Profile Condition="'$(Profile)' == ''">$(AppData)\Thunderstore Mod Manager\DataFolder\ROUNDS\profiles\Default</Profile>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp"><HintPath>$(GameManaged)\Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>$(GameManaged)\UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(GameManaged)\UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Photon3Unity3D"><HintPath>$(GameManaged)\Photon3Unity3D.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="PhotonUnityNetworking"><HintPath>$(GameManaged)\PhotonUnityNetworking.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="PhotonRealtime"><HintPath>$(GameManaged)\PhotonRealtime.dll</HintPath><Private>false</Private></Reference>

    <Reference Include="BepInEx"><HintPath>$(Profile)\BepInEx\core\BepInEx.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>$(Profile)\BepInEx\core\0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnboundLib"><HintPath>$(Profile)\BepInEx\plugins\willis81808-UnboundLib\UnboundLib.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>

</Project>
